---
title: "Stat 763 HW 2 Part 1"
author: "Matt Allen"
date: "2/15/2020"
output: html_document
---

```{r change_file_names_here, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#update the name of your file here
#heights filename
heights_file_name <- 'heights.pdf'
#ice cream filename
ice_cream_file_name <- 'ice_cream.csv'
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#built in stat 763 container
#used example here to install poppler to container OS.
#poppler is needed for pdftools
#https://github.com/aabor/rstudio/blob/master/rstudio-text/Dockerfile

library(tidyverse)
library(pdftools)
library(lubridate)
```

```{r my_functions, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

#function to clean heights data that are in feet and inches
clean_heights <- function(height_text) {
  #attempt to convert to numeric for all data.
  converted_heights <- as.numeric(height_text)
  
  #change any heights that may have been entered in ft to inches
  entered_as_feet = which(converted_heights >= 5 & converted_heights <= 7)
  converted_heights[entered_as_feet] = converted_heights[entered_as_feet]*12

  #regex exception patterns
  patterns = c("\\s*['\\s]+\\s*", 
               "\\s*ft\\s*", 
               "\\s*feet\\s*", 
               "\\s*\\*\\s*", 
               "\\s*\\,\\s*", 
               "\\s+\\.\\s*",
               "\\s+feet and\\s*")
  
  #go through the patterns and find and convert the numbers
  for(p in patterns) {
    number_pattern = paste0("\\d",p,"\\d*")
    if(any(str_detect(heights_text, number_pattern))) {
      ft_inches_which = str_which(height_text,pattern = number_pattern)
      pattern_to_split = heights$height_text[ft_inches_which]
      split_data = str_split(pattern_to_split,p, simplify = TRUE)
    
      #take the feet part multiply by 12 and add the inches part to it
      converted_heights[ft_inches_which] = as.numeric(str_trim(split_data[,1]))*12 +   as.numeric(str_trim(str_extract(split_data[,2],"\\d*")))
    }
  }
  return(converted_heights)
}

#function to convert to cm
convert_cm_heights <- function(height_text, converted_heights) {
  cm_which = str_which(height_text,pattern = "cm$")
  cm_heights_converted_to_inches = as.numeric(str_split(height_text[cm_which],"cm$",simplify = TRUE)[,1])*0.393701
  converted_heights[cm_which] = cm_heights_converted_to_inches
  return(converted_heights)
}

```

```{r data_clean, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

#--start create tibble for ice cream--#
ice_cream <- read.csv2(paste(getwd(),ice_cream_file_name,sep="/")
                       ,sep=",") %>%
  separate(preference, c("Preference_1","Preference_2","Preference_3"), 
           sep = ",", remove = TRUE, convert = FALSE, extra = "warn", fill = "warn") %>%
  mutate_all(str_trim)

#--start create tibble for height--#
heights <- pdf_text(paste(getwd(),heights_file_name,sep="/")) %>%
  read_lines()

#get rid of empty rows
heights <- heights[which(str_length(heights) > 0)]

#split data by Male and Female
split_on_sex <- str_split(heights[2:length(heights)],"Male|Female", simplify = TRUE)

#convert dates after split
dates <- mdy_hm(split_on_sex[1:length(heights)-1,1])

#get ids
ids <- str_extract(split_on_sex[1:length(heights)-1,2],"([a-zA-Z0-9_]+)$")

#get the heights text
#takes second column of split_on_sex
#and gets substr from beginning of string
#to (the length of the entire string - the length of the id)
heights_text <- str_sub(split_on_sex[1:length(heights)-1,2], 
                        1,
                        str_length(split_on_sex[1:length(heights)-1,2])-str_length(ids)) %>%
                str_squish() %>%
                str_trim()  %>%
                str_replace("^6'$","72") %>%
                str_replace("^Five foot eight inches$","68")  %>%
                str_replace("\"","")

#pull Male and Female from data
sex <- str_extract(heights[2:length(heights)],"Male|Female")

#make tibble from vector created above
heights <- tibble(id = ids, reported_date = dates, sex = sex, 
                  height_text = heights_text)



#clean up feet and height data
cleaned_heigths_data <- clean_heights(heights$height_text)

#convert cm height data
cleaned_heigths_data <- convert_cm_heights(heights$height_text, cleaned_heigths_data)

#add cleaned heights to heights table
heights$cleaned_heigths_data <- cleaned_heigths_data

#join heights and ice cream data
students_ice_cream_heights <- full_join(ice_cream, heights, by = c("student_IDs" = "id"))

#write to file
write.csv(students_ice_cream_heights,"cleaned_ice_cream_full_join_heights.csv")
```