---
title: "A Brief History of the Tour De France"
output: 
  flexdashboard::flex_dashboard:
    theme: cerulean
    orientation: rows
---

[Tour De France Data Source](https://github.com/alastairrushworth/tdf)

```{r setup, include=FALSE}
##dashboard was built using the Docker image stat763/verse:1.0

#data set can be installed by running command below
#devtools::install_github("alastairrushworth/tdf")

library(tidyverse)
library(flexdashboard)
library(lubridate)
library(DT) #Datatable
library(plotly)
library(tdf) #Tour De France Data

#tally up the number of stages for each edition.
#there is a column in the editions data set that is a list of lists
#this code unnests, does a tally and then does inner join back to original data set
#not sure if there is a better way to do this?
num_stages <- editions %>% 
  unnest(stage_results) %>% 
  group_by(start_date)  %>% 
  tally(name = "num_stages")
editions_join_stage <- editions %>% 
  inner_join(num_stages)

#create month and year columns and subset the original data set.
tdf_data <- mutate(editions_join_stage, year = year(start_date), month = month(start_date)) %>%
  select(edition,year,month,winner_name,nickname,age, distance,time_overall,time_margin,stage_wins,stages_led,height,weight,age,nationality,num_stages)
```

Row
-----------------------------------------------------------------------

### The earliest editions of the Tour de France had very few stages compared to today ...


```{r}
num_stages_plot <- ggplot(data = tdf_data) +
  geom_point(mapping= aes(x = year, y =  num_stages)) + 
  xlab('Year of Race') + 
  ylab('Number of Stages') + 
  ggtitle('Number of Stages by Year')
  
ggplotly(num_stages_plot)
```

### ... but they were really long by today's standards. Note the breaks for World War I and II.


```{r}
ave_stage_distance <- ggplot(data = tdf_data) +
  geom_point(mapping= aes(x = year, y =  distance / num_stages), 
             color = ifelse(tdf_data$year == 1914 | tdf_data$year == 1919 | tdf_data$year == 1939 | tdf_data$year == 1947,"red","black")) + 
  xlab('Year of Race') + 
  ylab('Total Distance (km) / Number of Stages') + 
  ggtitle('Average Length of Stages by Year') +
  annotate("text", x = 1917, y = 380, label = "World War I", size = 3) +
  annotate("text", x = 1943, y = 145, label = "World War II", size = 3) +
  annotate("rect", xmin = 1914, xmax = 1919, ymin = 358, ymax = 370,alpha = .2) +
  annotate("rect", xmin = 1939, xmax = 1947, ymin = 162, ymax = 221,alpha = .2)
 

ggplotly(ave_stage_distance)
```

Row
-----------------------------------------------------------------------

### The French have the most wins, but there has been a drought since 1985 when Bernard Hinault (the Badger) won.

```{r}
#make table of win counts by nationality
winners_nationality <- tdf_data %>%
  select(nationality) %>% #select(year, winner_name, nickname, age, nationality)
  group_by(nationality) %>%
  tally(name = "Number Wins")

#make table with nationality and last year won
last_year_by_nationality <- tdf_data %>% 
  select(nationality, year) %>%
  group_by(nationality) %>%
  filter(year == max(year))

#join the two and rename
winner_nationality_last_year <- winners_nationality %>% 
  inner_join(last_year_by_nationality) %>%
  arrange(desc(`Number Wins`)) %>% 
  rename(`Nationality` = nationality, `Last Year Won` = year )  

#create datatable
datatable(winner_nationality_last_year, options = list(pageLength = 20), rownames = FALSE)

```

### The French last win in 1985 came the year before Greg LeMond (L’Americain) slayed the Badger, and six years before the doping era, which was ended by another American.

```{r}
tdf_data_1985_2005 <- tdf_data %>%
  filter(year >= 1985 & year <= 2005)

#http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette
cbPalette <- c("#000000","#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


ave_speed <- ggplot(data = tdf_data_1985_2005) +
  geom_point(mapping= aes(x = year, y =  distance / time_overall, color = winner_name)) + 
  xlab('Year of Race') + 
  ylab('Average Speed (km/h)') + 
  ggtitle('Average Speed by Winner Over Entire Race') +
  labs(color = "Winner Name") +
  scale_colour_manual(values=cbPalette)
  
ggplotly(ave_speed)
```

